[phases.setup]
commands = [
  "cd backend"
]

[phases.build]
commands = [
  "cd backend",
  "./mvnw clean package -DskipTests"
]

[phases.install]
commands = []

[phases.start]
commands = [
  "./start.sh"
]

[env]
PORT = "8080"
