[phases.setup]
commands = [
  "cd backend"
]

[phases.build]
commands = [
  "cd backend",
  "./mvnw clean package -DskipTests"
]

[phases.install]
commands = []

[phases.start]
commands = [
  "cd backend && java -jar target/*.jar"
]

[env]
PORT = "8080"
