app.base-url=${APP_BASE_URL:http://localhost:8080}
spring.application.name=cartoonframe
spring.profiles.active=${APP_PROFILE}
spring.jpa.open-in-view=false

cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

api.security.token.secret=${SECURITY_TOKEN_SECRET}

# Configurações do servidor SMTP do Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_EMAIL}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.default-encoding=UTF-8
