spring.application.name=cartoonframe
spring.profiles.active=${APP_PROFILE:test}
spring.jpa.open-in-view=false

cors.origins=${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}

spring.datasource.url=***REMOVED***
spring.datasource.username=***REMOVED***
spring.datasource.password=***REMOVED***
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=teste

# Configurações do servidor SMTP do Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=***REMOVED***
spring.mail.password=***REMOVED***
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Opcional (mas recomendável)
spring.mail.default-encoding=UTF-8

spring.mail.properties.mail.debug=true
logging.level.org.springframework.mail=DEBUG
logging.level.com.sun.mail=DEBUG
